server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - RewritePath=/hotels/(?<path>.*), /$\{path}

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - RewritePath=/ratings/(?<path>.*), /$\{path}

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway

# okta:
#   oauth2:
#     issuer: https://dev-77584981.okta.com/oauth2/default
#     audience: api://default
#     client-id: 0oa7w65a24Px9Oyms5d7
#     client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU
#     scopes: openid, profile, email, offline_access

springdoc:
  swagger-ui:
    urls:
      - name: users
        url: /v3/api-docs/users
      - name: hotels
        url: /v3/api-docs/hotels
      - name: ratings
        url: /v3/api-docs/ratings
    use-root-path: true